CREATE TABLE CLIENTE(
	IDcliente INT NOT NULL,
	Usuario VARCHAR(20) NOT NULL,
	Contraseña VARCHAR(64) NOT NULL,
	InfoContacto VARCHAR(100) NOT NULL,
	Nombre VARCHAR(40) NOT NULL,
	email VARCHAR(30) NOT NULL,
	PuntosDispo INT NOT NULL
);

ALTER TABLE CLIENTE
ADD PRIMARY KEY (IDCliente,Usuario);

Select * from CLIENTE